# Generated by Django 3.1.12 on 2021-09-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_category',
            new_name='category',
        ),
    ]
