# Generated by Django 3.1.12 on 2021-09-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20210918_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
