# Generated by Django 3.1.12 on 2021-09-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.sub_category'),
        ),
    ]
