# Generated by Django 3.1.12 on 2021-09-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='un',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
